{
 "title": "GPU Utilization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "instance",
    "query": {
     "query": "label_values({__name__=~\"gpu_clock_mhz\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Power Consumption(W)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gpu_power_watts{instance=\"$Instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Power Consumption (W)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "gpu_power_watts{instance=\"$Instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Instance",
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature(°C)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gpu_temperature_celsius{instance=\"$Instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GPU Temperature(°C)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "gpu_temperature_celsius{instance=\"$Instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "vRAM Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "Instance" },
  {
   "title": "vRAM Usage(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_memory_utilization_percent{instance=\"$Instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "vRAM Usage(MiB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_memory_used_mib{instance=\"$Instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "GPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Instance" },
  {
   "title": "GPU Utilisation(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_percent{instance=\"$Instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GPU Clock(MHz)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "gpu_clock_mhz{instance=\"$Instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}